services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=demo
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
